--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: command_log; Type: TABLE; Schema: editor; Owner: postgres
--

CREATE TABLE editor.command_log (
    id bigint NOT NULL,
    user_name character varying(255),
    entity_type character varying(255),
    entity_id bigint,
    command_type character varying(255),
    payload jsonb,
    undo_payload jsonb,
    created_at timestamp without time zone,
    user_id bigint,
    batch_id uuid,
    sequence integer,
    undone_at timestamp(6) without time zone
);


ALTER TABLE editor.command_log OWNER TO postgres;

--
-- Name: command_log_id_seq; Type: SEQUENCE; Schema: editor; Owner: postgres
--

ALTER TABLE editor.command_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME editor.command_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: command_log; Type: TABLE DATA; Schema: editor; Owner: postgres
--

COPY editor.command_log (id, user_name, entity_type, entity_id, command_type, payload, undo_payload, created_at, user_id, batch_id, sequence, undone_at) FROM stdin;
172	david	component	1	CREATE_COMPONENT	{"ids": [838, 839, 840, 841, 842, 843, 844, 845, 897, 898, 899, 900, 901, 902, 903, 904]}	{"ids": [838, 839, 840, 841, 842, 843, 844, 845, 897, 898, 899, 900, 901, 902, 903, 904]}	2026-06-21 22:59:42.620214	\N	\N	\N	\N
173	david	component_property	19	CREATE_PROPERTY	{"id": 19}	{"id": 19}	2026-06-21 23:00:17.369507	\N	\N	\N	\N
174	david	component	1	CREATE_COMPONENT	{"ids": [247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796]}	{"ids": [247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796]}	2026-06-23 09:03:24.804206	\N	\N	\N	\N
175	david	component	905	CREATE_SCENE	{"id": 905}	{"id": 905}	2026-06-23 20:34:01.338787	\N	\N	\N	\N
176	david	component	906	CREATE_SCENE	{"id": 906}	{"id": 906}	2026-06-23 20:40:19.787969	\N	\N	\N	\N
177	david	component	1	CREATE_COMPONENT	{"ids": [907, 908]}	{"ids": [907, 908]}	2026-06-23 20:46:47.828685	\N	\N	\N	\N
178	david	component	1	CREATE_COMPONENT	{"ids": []}	{"ids": []}	2026-06-23 20:48:01.329909	\N	\N	\N	\N
179	david	component	909	CREATE_PROJECT	{"id": 909}	{"id": 909}	2026-06-23 20:53:18.077059	\N	\N	\N	\N
180	david	component	910	CREATE_SCENE	{"id": 910}	{"id": 910}	2026-06-23 20:53:30.351147	\N	\N	\N	\N
181	david	component	911	CREATE_PROJECT	{"id": 911}	{"id": 911}	2026-06-23 20:56:11.060256	\N	\N	\N	\N
182	david	component	912	CREATE_SCENE	{"id": 912}	{"id": 912}	2026-06-23 20:56:16.129959	\N	\N	\N	\N
183	david	component	1	CREATE_COMPONENT	{"ids": [913, 914, 915]}	{"ids": [913, 914, 915]}	2026-06-23 20:58:40.031506	\N	\N	\N	\N
184	david	component	916	CREATE_SCENE	{"id": 916}	{"id": 916}	2026-06-23 20:58:47.975787	\N	\N	\N	\N
185	david	component	1	CREATE_COMPONENT	{"ids": []}	{"ids": []}	2026-06-23 20:59:40.872197	\N	\N	\N	\N
186	david	component	1	CREATE_COMPONENT	{"ids": [917, 918]}	{"ids": [917, 918]}	2026-06-23 20:59:48.218791	\N	\N	\N	\N
187	david	component	1	CREATE_COMPONENT	{"ids": [919, 917, 918]}	{"ids": [919, 917, 918]}	2026-06-23 21:01:53.738482	\N	\N	\N	\N
188	david	component	1	CREATE_COMPONENT	{"ids": [920, 917, 918]}	{"ids": [920, 917, 918]}	2026-06-23 21:02:12.963858	\N	\N	\N	\N
189	david	component	921	CREATE_PROJECT	{"id": 921}	{"id": 921}	2026-06-23 21:04:45.025025	\N	\N	\N	\N
190	david	component	1	CREATE_COMPONENT	{"ids": [913, 914, 915, 922, 923, 924]}	{"ids": [913, 914, 915, 922, 923, 924]}	2026-06-23 21:04:54.703773	\N	\N	\N	\N
191	david	component	1	CREATE_COMPONENT	{"ids": [913, 914, 915, 925, 926, 927, 928, 929, 930]}	{"ids": [913, 914, 915, 925, 926, 927, 928, 929, 930]}	2026-06-23 21:05:20.2282	\N	\N	\N	\N
192	david	component	1	CREATE_COMPONENT	{"ids": [913, 914, 915, 931, 932, 933, 934]}	{"ids": [913, 914, 915, 931, 932, 933, 934]}	2026-06-23 21:15:06.43705	\N	\N	\N	\N
193	david	component_property	20	CREATE_PROPERTY	{"id": 20}	{"id": 20}	2026-06-23 21:17:37.00066	\N	\N	\N	\N
194	david	component	1	CREATE_COMPONENT	{"ids": []}	{"ids": []}	2026-06-23 21:21:55.843842	\N	\N	\N	\N
195	david	component	1	CREATE_COMPONENT	{"ids": [935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949]}	{"ids": [935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949]}	2026-06-23 21:28:29.785981	\N	\N	\N	\N
196	david	component	950	CREATE_PROJECT	{"id": 950}	{"id": 950}	2026-07-20 09:26:14.022256	\N	\N	\N	\N
197	david	component	951	CREATE_SCENE	{"id": 951}	{"id": 951}	2026-07-20 09:26:55.823287	\N	\N	\N	\N
198	david	component	\N	CREATE_COMPONENT	{"ids": []}	{"ids": []}	2026-07-20 09:27:34.476413	\N	\N	\N	\N
199	david	component	\N	CREATE_COMPONENT	{"ids": [952]}	{"ids": [952]}	2026-07-20 09:28:34.414613	\N	\N	\N	\N
200	david	component	\N	CREATE_COMPONENT	{"ids": [952, 953, 954, 955, 956]}	{"ids": [952, 953, 954, 955, 956]}	2026-07-20 09:29:34.411927	\N	\N	\N	\N
201	david	component	\N	CREATE_COMPONENT	{"ids": [957]}	{"ids": [957]}	2026-07-20 09:30:34.408967	\N	\N	\N	\N
202	david	component	\N	DELETE_COMPONENT	{"ids": [952, 953, 954, 955, 956]}	{"ids": [952, 953, 954, 955, 956]}	2026-07-20 09:30:54.247501	\N	\N	\N	\N
203	david	component	\N	CREATE_COMPONENT	{"ids": [957, 958]}	{"ids": [957, 958]}	2026-07-20 09:31:34.422836	\N	\N	\N	\N
204	david	component	\N	CREATE_COMPONENT	{"ids": [957, 958]}	{"ids": [957, 958]}	2026-07-20 09:32:34.414409	\N	\N	\N	\N
205	david	component	\N	CREATE_COMPONENT	{"ids": [957, 958, 959]}	{"ids": [957, 958, 959]}	2026-07-20 09:34:34.40924	\N	\N	\N	\N
206	david	component	\N	CREATE_COMPONENT	{"ids": [957, 958, 959]}	{"ids": [957, 958, 959]}	2026-07-20 09:35:34.412584	\N	\N	\N	\N
207	david	component	\N	CREATE_COMPONENT	{"ids": [957, 958, 959, 960, 961]}	{"ids": [957, 958, 959, 960, 961]}	2026-07-20 09:36:34.421587	\N	\N	\N	\N
208	david	component	\N	CREATE_COMPONENT	{"ids": [957, 958]}	{"ids": [957, 958]}	2026-07-20 09:37:34.426938	\N	\N	\N	\N
209	david	component	\N	DELETE_COMPONENT	{"ids": [959]}	{"ids": [959]}	2026-07-20 09:37:45.268688	\N	\N	\N	\N
210	david	component	\N	DELETE_COMPONENT	{"ids": [960, 961]}	{"ids": [960, 961]}	2026-07-20 09:38:29.157062	\N	\N	\N	\N
211	david	component	\N	DELETE_COMPONENT	{"ids": [959]}	{"ids": [959]}	2026-07-20 09:38:30.191581	\N	\N	\N	\N
212	david	component	\N	CREATE_COMPONENT	{"ids": [957, 958]}	{"ids": [957, 958]}	2026-07-20 09:38:34.416794	\N	\N	\N	\N
213	david	component	\N	CREATE_COMPONENT	{"ids": [957]}	{"ids": [957]}	2026-07-20 09:39:34.425904	\N	\N	\N	\N
214	david	component	\N	DELETE_COMPONENT	{"ids": [958]}	{"ids": [958]}	2026-07-20 09:39:47.322382	\N	\N	\N	\N
215	david	component	\N	CREATE_COMPONENT	{"ids": [957]}	{"ids": [957]}	2026-07-20 09:40:34.413918	\N	\N	\N	\N
216	david	component	\N	CREATE_COMPONENT	{"ids": [957, 962]}	{"ids": [957, 962]}	2026-07-21 12:18:59.217981	\N	\N	\N	\N
217	david	component	\N	CREATE_COMPONENT	{"ids": [957, 962, 963, 964, 965, 966]}	{"ids": [957, 962, 963, 964, 965, 966]}	2026-07-21 12:22:59.12772	\N	\N	\N	\N
218	david	component	\N	DELETE_COMPONENT	{"ids": [965]}	{"ids": [965]}	2026-07-21 12:23:23.600322	\N	\N	\N	\N
219	david	component	\N	DELETE_COMPONENT	{"ids": [964]}	{"ids": [964]}	2026-07-21 12:23:25.322944	\N	\N	\N	\N
220	david	component	\N	CREATE_COMPONENT	{"ids": [957, 962, 967]}	{"ids": [957, 962, 967]}	2026-07-21 12:23:59.117433	\N	\N	\N	\N
221	david	component	\N	DELETE_COMPONENT	{"ids": [963, 966]}	{"ids": [963, 966]}	2026-07-21 12:24:07.685273	\N	\N	\N	\N
222	david	component	\N	CREATE_COMPONENT	{"ids": [957, 962, 967]}	{"ids": [957, 962, 967]}	2026-07-21 12:24:24.976824	\N	\N	\N	\N
223	david	component	\N	CREATE_COMPONENT	{"ids": [967, 957, 962]}	{"ids": [967, 957, 962]}	2026-07-21 12:24:25.564916	\N	\N	\N	\N
224	david	component	\N	CREATE_COMPONENT	{"ids": [967, 957, 962]}	{"ids": [967, 957, 962]}	2026-07-21 12:24:59.11263	\N	\N	\N	\N
225	david	component	\N	CREATE_COMPONENT	{"ids": [967, 957, 962]}	{"ids": [967, 957, 962]}	2026-07-21 12:26:59.558461	\N	\N	\N	\N
226	david	component	\N	CREATE_COMPONENT	{"ids": [967, 957, 962]}	{"ids": [967, 957, 962]}	2026-07-21 12:27:59.12456	\N	\N	\N	\N
227	david	component	\N	CREATE_COMPONENT	{"ids": [967, 957, 962]}	{"ids": [967, 957, 962]}	2026-07-21 12:28:59.11846	\N	\N	\N	\N
228	david	component	\N	CREATE_COMPONENT	{"ids": [967, 957, 962]}	{"ids": [967, 957, 962]}	2026-07-21 12:29:00.027516	\N	\N	\N	\N
229	david	component	\N	CREATE_COMPONENT	{"ids": [967, 957, 962]}	{"ids": [967, 957, 962]}	2026-07-21 12:29:29.238283	\N	\N	\N	\N
230	david	component	\N	CREATE_COMPONENT	{"ids": [967, 957, 962]}	{"ids": [967, 957, 962]}	2026-07-21 12:29:59.111211	\N	\N	\N	\N
231	david	component	\N	CREATE_COMPONENT	{"ids": [967, 957, 962]}	{"ids": [967, 957, 962]}	2026-07-21 14:42:59.5013	\N	\N	\N	\N
232	david	component	\N	CREATE_COMPONENT	{"ids": [967, 957, 962, 968]}	{"ids": [967, 957, 962, 968]}	2026-07-21 14:43:59.483129	\N	\N	\N	\N
233	david	component	\N	CREATE_COMPONENT	{"ids": [968, 967, 957, 962]}	{"ids": [968, 967, 957, 962]}	2026-07-21 14:44:59.485968	\N	\N	\N	\N
234	david	component	\N	CREATE_COMPONENT	{"ids": [968, 967, 957, 962]}	{"ids": [968, 967, 957, 962]}	2026-07-21 14:45:59.490066	\N	\N	\N	\N
235	david	component	\N	CREATE_COMPONENT	{"ids": [968, 967, 957, 962]}	{"ids": [968, 967, 957, 962]}	2026-07-21 14:46:59.481942	\N	\N	\N	\N
236	david	component	\N	CREATE_COMPONENT	{"ids": [968, 967, 957, 962]}	{"ids": [968, 967, 957, 962]}	2026-07-21 14:47:59.491308	\N	\N	\N	\N
237	david	component	\N	CREATE_COMPONENT	{"ids": [968, 967, 957, 962]}	{"ids": [968, 967, 957, 962]}	2026-07-21 14:48:59.482239	\N	\N	\N	\N
238	david	component	\N	CREATE_COMPONENT	{"ids": [967, 957, 968, 962]}	{"ids": [967, 957, 968, 962]}	2026-07-21 14:49:59.495313	\N	\N	\N	\N
239	david	component	\N	DELETE_COMPONENT	{"ids": [967]}	{"ids": [967]}	2026-07-21 14:50:09.016474	\N	\N	\N	\N
277	e2e_tester	component	981	CREATE_SCENE	{"id": 981}	{"id": 981}	2026-07-27 16:53:30.60794	\N	\N	\N	\N
240	david	component	\N	CREATE_COMPONENT	{"ids": [957, 968, 962, 969]}	{"ids": [957, 968, 962, 969]}	2026-07-21 14:50:59.485363	\N	\N	\N	\N
241	david	component	\N	DELETE_COMPONENT	{"ids": [969]}	{"ids": [969]}	2026-07-21 14:51:13.204422	\N	\N	\N	\N
242	david	component	\N	CREATE_COMPONENT	{"ids": [957, 968, 962]}	{"ids": [957, 968, 962]}	2026-07-21 14:51:59.486158	\N	\N	\N	\N
243	david	component	\N	CREATE_COMPONENT	{"ids": [957, 968, 962, 970, 971]}	{"ids": [957, 968, 962, 970, 971]}	2026-07-21 14:52:59.483096	\N	\N	\N	\N
244	david	component	\N	CREATE_COMPONENT	{"ids": [957, 968, 962, 972, 970, 971]}	{"ids": [957, 968, 962, 972, 970, 971]}	2026-07-21 14:53:59.485297	\N	\N	\N	\N
245	david	component	\N	CREATE_COMPONENT	{"ids": [972, 970, 971, 957, 968, 962]}	{"ids": [972, 970, 971, 957, 968, 962]}	2026-07-21 14:54:59.500221	\N	\N	\N	\N
246	david	component	\N	CREATE_COMPONENT	{"ids": [972, 970, 971, 957, 968, 962]}	{"ids": [972, 970, 971, 957, 968, 962]}	2026-07-21 14:55:27.950021	\N	\N	\N	\N
247	david	component	\N	CREATE_COMPONENT	{"ids": [972, 970, 971, 957, 968, 962]}	{"ids": [972, 970, 971, 957, 968, 962]}	2026-07-21 14:55:59.487066	\N	\N	\N	\N
248	david	component	\N	CREATE_COMPONENT	{"ids": [972, 970, 971, 957, 968, 962]}	{"ids": [972, 970, 971, 957, 968, 962]}	2026-07-21 14:57:14.180392	\N	\N	\N	\N
249	david	component	\N	CREATE_COMPONENT	{"ids": [972, 970, 971, 957, 968, 962]}	{"ids": [972, 970, 971, 957, 968, 962]}	2026-07-21 14:57:59.485064	\N	\N	\N	\N
250	david	template	32	CREATE_TEMPLATE	\N	\N	2026-07-21 14:58:01.304468	\N	\N	\N	\N
251	david	component	\N	CREATE_COMPONENT	{"ids": [972, 970, 971, 957, 968, 962]}	{"ids": [972, 970, 971, 957, 968, 962]}	2026-07-21 14:58:59.48414	\N	\N	\N	\N
252	david	component	\N	CREATE_COMPONENT	{"ids": [957, 968, 972, 970, 971, 962]}	{"ids": [957, 968, 972, 970, 971, 962]}	2026-07-21 14:59:59.494374	\N	\N	\N	\N
253	david	component	\N	CREATE_COMPONENT	{"ids": [957, 968, 972, 970, 971, 962]}	{"ids": [957, 968, 972, 970, 971, 962]}	2026-07-21 15:00:59.481884	\N	\N	\N	\N
254	david	component	\N	CREATE_COMPONENT	{"ids": [957, 968, 972, 970, 971, 962]}	{"ids": [957, 968, 972, 970, 971, 962]}	2026-07-21 15:01:12.885346	\N	\N	\N	\N
255	david	template	33	CREATE_TEMPLATE	\N	\N	2026-07-21 15:03:35.425865	\N	\N	\N	\N
256	david	component	\N	CREATE_COMPONENT	{"ids": [957, 968, 972, 970, 971, 962, 973, 974, 975]}	{"ids": [957, 968, 972, 970, 971, 962, 973, 974, 975]}	2026-07-21 15:03:40.948019	\N	\N	\N	\N
257	david	component	\N	DELETE_COMPONENT	{"ids": [973, 974, 975]}	{"ids": [973, 974, 975]}	2026-07-21 15:04:26.975887	\N	\N	\N	\N
258	david	template	34	CREATE_TEMPLATE	\N	\N	2026-07-21 15:05:43.949112	\N	\N	\N	\N
259	david	template	34	DELETE_TEMPLATE	\N	\N	2026-07-21 15:07:31.04877	\N	\N	\N	\N
260	david	template	33	DELETE_TEMPLATE	\N	\N	2026-07-21 15:07:31.360905	\N	\N	\N	\N
261	david	component_property	21	CREATE_PROPERTY	{"id": 21}	{"id": 21}	2026-07-21 15:08:49.524437	\N	\N	\N	\N
262	david	component_property	22	CREATE_PROPERTY	{"id": 22}	{"id": 22}	2026-07-21 15:09:16.56302	\N	\N	\N	\N
263	david	component_property	23	CREATE_PROPERTY	{"id": 23}	{"id": 23}	2026-07-21 15:10:34.727009	\N	\N	\N	\N
264	david	component	\N	CREATE_COMPONENT	{"ids": [957, 968, 972, 970, 971, 962]}	{"ids": [957, 968, 972, 970, 971, 962]}	2026-07-21 15:10:49.095408	\N	\N	\N	\N
265	david	component	\N	CREATE_COMPONENT	{"ids": [957, 968, 972, 970, 971, 962]}	{"ids": [957, 968, 972, 970, 971, 962]}	2026-07-21 15:18:07.300341	\N	\N	\N	\N
266	david	component	\N	CREATE_COMPONENT	{"ids": [957, 968, 972, 970, 971, 962]}	{"ids": [957, 968, 972, 970, 971, 962]}	2026-07-22 15:11:07.548816	\N	\N	\N	\N
267	david	component	\N	CREATE_COMPONENT	{"ids": [957, 968, 972, 970, 971, 962]}	{"ids": [957, 968, 972, 970, 971, 962]}	2026-07-22 15:30:24.252579	\N	\N	\N	\N
268	david	component	\N	CREATE_COMPONENT	{"ids": [957, 968, 972, 970, 971, 962]}	{"ids": [957, 968, 972, 970, 971, 962]}	2026-07-22 15:35:57.470613	\N	\N	\N	\N
269	david	component	\N	CREATE_COMPONENT	{"ids": [957, 968, 972, 970, 971, 962]}	{"ids": [957, 968, 972, 970, 971, 962]}	2026-07-22 15:45:07.729924	\N	\N	\N	\N
270	claude	component	\N	UPDATE_COMPONENT	{"ids": [962]}	{"ids": [962]}	2026-07-23 15:27:43.076699	\N	\N	\N	\N
271	claude	component	\N	CREATE_COMPONENT	{"ids": [976]}	{"ids": [976]}	2026-07-23 15:30:38.651924	\N	\N	\N	\N
272	claude	component	\N	DELETE_COMPONENT	{"ids": [976]}	{"ids": [976]}	2026-07-23 15:31:07.300455	\N	\N	\N	\N
273	e2e_tester	component	977	CREATE_PROJECT	{"id": 977}	{"id": 977}	2026-07-27 16:02:40.137536	\N	\N	\N	\N
274	e2e_tester	component	978	CREATE_SCENE	{"id": 978}	{"id": 978}	2026-07-27 16:02:40.240538	\N	\N	\N	\N
275	e2e_tester	component	\N	CREATE_COMPONENT	{"ids": [979]}	{"ids": [979]}	2026-07-27 16:02:40.305538	\N	\N	\N	\N
276	e2e_tester	component	980	CREATE_PROJECT	{"id": 980}	{"id": 980}	2026-07-27 16:53:30.517938	\N	\N	\N	\N
278	e2e_tester	component	\N	CREATE_COMPONENT	{"ids": [982]}	{"ids": [982]}	2026-07-27 16:53:30.671943	\N	\N	\N	\N
279	david	component	\N	CREATE_COMPONENT	{"ids": [979, 983]}	{"ids": [979, 983]}	2026-07-29 08:51:53.085617	\N	\N	\N	\N
280	david	component	\N	CREATE_COMPONENT	{"ids": [979, 983]}	{"ids": [979, 983]}	2026-07-29 11:26:46.723637	\N	\N	\N	\N
281	david	component	\N	CREATE_COMPONENT	{"ids": [979, 983]}	{"ids": [979, 983]}	2026-07-29 11:33:47.467953	\N	\N	\N	\N
282	david	component	\N	CREATE_COMPONENT	{"ids": [979, 983]}	{"ids": [979, 983]}	2026-07-29 11:35:52.598404	\N	\N	\N	\N
283	david	component	\N	CREATE_COMPONENT	{"ids": [979, 983]}	{"ids": [979, 983]}	2026-07-29 11:40:22.058948	\N	\N	\N	\N
284	david	component	\N	CREATE_COMPONENT	{"ids": [979, 983]}	{"ids": [979, 983]}	2026-07-29 11:49:56.816735	\N	\N	\N	\N
285	verify	component_property	50	CREATE_PROPERTY	{"id": 50}	{"id": 50}	2026-07-30 16:41:32.822455	\N	\N	\N	\N
286	verify	component_property	50	UPDATE_PROPERTY	{"id": 50}	{"id": 50, "name": "Локальная уставка", "tag_id": null, "logging": false, "onChange": null, "position": null, "value_type": "number", "description": null, "component_id": 982, "default_value": "0", "property_type": "Локальный"}	2026-07-30 16:41:58.109085	\N	\N	\N	\N
287	verify	component_property	50	DELETE_PROPERTY	{"id": 50}	{"id": 50}	2026-07-30 16:42:11.301801	\N	\N	\N	\N
288	e2e	component_property	51	CREATE_PROPERTY	{"id": 51}	{"id": 51}	2026-07-30 16:46:35.555425	\N	\N	\N	\N
289	e2e	component_property	51	DELETE_PROPERTY	{"id": 51}	{"id": 51}	2026-07-30 16:53:00.733398	\N	\N	\N	\N
290	david	component	984	CREATE_SCENE	{"id": 984}	{"id": 984}	2026-07-31 16:18:59.341779	\N	\N	\N	\N
291	david	component	\N	CREATE_COMPONENT	{"ids": [985]}	{"ids": [985]}	2026-07-31 16:20:34.072485	\N	\N	\N	\N
292	david	component_property	52	CREATE_PROPERTY	{"id": 52}	{"id": 52}	2026-07-31 16:20:58.809132	\N	\N	\N	\N
293	david	component	\N	CREATE_COMPONENT	{"ids": [985]}	{"ids": [985]}	2026-07-31 16:21:02.996458	\N	\N	\N	\N
294	david	component_property	54	CREATE_PROPERTY	{"id": 54}	{"id": 54}	2026-07-31 16:38:29.043115	\N	\N	\N	\N
295	david	component	\N	CREATE_COMPONENT	{"ids": [985]}	{"ids": [985]}	2026-07-31 16:38:31.397226	\N	\N	\N	\N
296	operator1	component	986	CREATE_PROJECT	{"id": 986}	{"id": 986}	2026-07-31 16:44:31.806273	\N	\N	\N	\N
297	operator1	component	987	CREATE_SCENE	{"id": 987}	{"id": 987}	2026-07-31 16:44:31.842274	\N	\N	\N	\N
298	operator1	component	\N	CREATE_COMPONENT	{"ids": [988]}	{"ids": [988]}	2026-07-31 16:44:31.864273	\N	\N	\N	\N
299	david	component	\N	CREATE_COMPONENT	{"ids": [988]}	{"ids": [988]}	2026-08-03 14:31:50.747675	\N	\N	\N	\N
300	david	component	\N	CREATE_COMPONENT	{"ids": [985]}	{"ids": [985]}	2026-08-03 15:32:21.396315	\N	\N	\N	\N
301	demo-setup	component	989	CREATE_PROJECT	{"id": 989}	{"id": 989}	2026-08-07 08:39:34.954977	\N	\N	\N	\N
302	demo-setup	component	990	CREATE_SCENE	{"id": 990}	{"id": 990}	2026-08-07 08:39:35.022971	\N	\N	\N	\N
303	demo-setup	component	\N	CREATE_COMPONENT	{"ids": [991, 992, 993]}	{"ids": [991, 992, 993]}	2026-08-07 08:39:35.077967	\N	\N	\N	\N
304	diag	component	\N	CREATE_COMPONENT	{"ids": [994]}	{"ids": [994]}	2026-08-07 08:41:06.663873	\N	\N	\N	\N
305	diag	component	\N	UPDATE_COMPONENT	{"ids": [994]}	{"ids": [994]}	2026-08-07 08:41:06.694403	\N	\N	\N	\N
306	diag	component	\N	UPDATE_COMPONENT	{"ids": [994]}	{"ids": [994]}	2026-08-07 08:41:06.736038	\N	\N	\N	\N
307	diag	component	\N	UPDATE_COMPONENT	{"ids": [994]}	{"ids": [994]}	2026-08-07 08:41:06.766033	\N	\N	\N	\N
308	diag	component	\N	DELETE_COMPONENT	{"ids": [994]}	{"ids": [994]}	2026-08-07 08:41:06.792031	\N	\N	\N	\N
309	diag	component	\N	UPDATE_COMPONENT	{"ids": [993]}	{"ids": [993]}	2026-08-07 08:41:54.733948	\N	\N	\N	\N
310	diag	component	\N	CREATE_COMPONENT	{"ids": [995]}	{"ids": [995]}	2026-08-07 08:42:24.404775	\N	\N	\N	\N
311	diag	component	\N	UPDATE_COMPONENT	{"ids": [995]}	{"ids": [995]}	2026-08-07 08:42:24.424783	\N	\N	\N	\N
312	diag	component	\N	UPDATE_COMPONENT	{"ids": [995]}	{"ids": [995]}	2026-08-07 08:42:24.447771	\N	\N	\N	\N
313	diag	component	\N	UPDATE_COMPONENT	{"ids": [995]}	{"ids": [995]}	2026-08-07 08:42:24.46977	\N	\N	\N	\N
314	diag	component	\N	DELETE_COMPONENT	{"ids": [995]}	{"ids": [995]}	2026-08-07 08:42:24.49183	\N	\N	\N	\N
315	diag	component	\N	UPDATE_COMPONENT	{"ids": [992]}	{"ids": [992]}	2026-08-07 08:42:55.971852	\N	\N	\N	\N
316	diag	component	\N	UPDATE_COMPONENT	{"ids": [992]}	{"ids": [992]}	2026-08-07 08:42:55.998845	\N	\N	\N	\N
317	diag	component	\N	UPDATE_COMPONENT	{"ids": [992]}	{"ids": [992]}	2026-08-07 08:42:56.027788	\N	\N	\N	\N
318	diag	component	\N	UPDATE_COMPONENT	{"ids": [992]}	{"ids": [992]}	2026-08-07 08:43:33.217908	\N	\N	\N	\N
319	diag	component	\N	UPDATE_COMPONENT	{"ids": [992]}	{"ids": [992]}	2026-08-07 08:43:33.238905	\N	\N	\N	\N
320	demo-setup	component	\N	UPDATE_COMPONENT	{"ids": [992, 993]}	{"ids": [992, 993]}	2026-08-07 08:44:00.799484	\N	\N	\N	\N
321	demo-setup	component	\N	UPDATE_COMPONENT	{"ids": [992]}	{"ids": [992]}	2026-08-07 08:44:49.041348	\N	\N	\N	\N
322	demo-setup	component	\N	UPDATE_COMPONENT	{"ids": [993]}	{"ids": [993]}	2026-08-07 08:44:49.064347	\N	\N	\N	\N
323	repro	component	\N	CREATE_COMPONENT	{"ids": [996]}	{"ids": [996]}	2026-08-07 09:13:52.910594	\N	\N	\N	\N
325	test	component	\N	CREATE_COMPONENT	{"ids": [997]}	{"ids": [997]}	2026-08-07 09:18:37.857228	\N	\N	\N	\N
326	test	component	\N	UPDATE_COMPONENT	{"ids": [997]}	{"ids": [997]}	2026-08-07 09:18:37.935167	\N	\N	\N	\N
327	test	component	\N	CREATE_COMPONENT	{"ids": [998]}	{"ids": [998]}	2026-08-07 09:18:37.967168	\N	\N	\N	\N
328	test	component	\N	UPDATE_COMPONENT	{"ids": [998]}	{"ids": [998]}	2026-08-07 09:18:37.994169	\N	\N	\N	\N
329	test	component	\N	UPDATE_COMPONENT	{"ids": [998]}	{"ids": [998]}	2026-08-07 09:18:38.019169	\N	\N	\N	\N
330	test	component	\N	UPDATE_COMPONENT	{"ids": [998]}	{"ids": [998]}	2026-08-07 09:18:38.046693	\N	\N	\N	\N
331	test	component	\N	CREATE_COMPONENT	{"ids": [999]}	{"ids": [999]}	2026-08-07 09:18:38.072541	\N	\N	\N	\N
332	test	component	\N	UPDATE_COMPONENT	{"ids": [999]}	{"ids": [999]}	2026-08-07 09:18:38.093319	\N	\N	\N	\N
333	test	component	\N	CREATE_COMPONENT	{"ids": [1000]}	{"ids": [1000]}	2026-08-07 09:18:38.117832	\N	\N	\N	\N
334	test	component	\N	CREATE_COMPONENT	{"ids": [1001]}	{"ids": [1001]}	2026-08-07 09:18:38.141831	\N	\N	\N	\N
335	test	component	\N	CREATE_COMPONENT	{"ids": [1002]}	{"ids": [1002]}	2026-08-07 09:18:38.191732	\N	\N	\N	\N
336	test	component	\N	CREATE_COMPONENT	{"ids": [1003]}	{"ids": [1003]}	2026-08-07 09:18:38.20429	\N	\N	\N	\N
337	test	component	\N	CREATE_COMPONENT	{"ids": [1004]}	{"ids": [1004]}	2026-08-07 09:18:38.233944	\N	\N	\N	\N
338	test	component	\N	UPDATE_COMPONENT	{"ids": [1004]}	{"ids": [1004]}	2026-08-07 09:18:38.265938	\N	\N	\N	\N
339	test	component	\N	CREATE_COMPONENT	{"ids": [1005]}	{"ids": [1005]}	2026-08-07 09:18:38.293272	\N	\N	\N	\N
340	test	component	\N	UPDATE_COMPONENT	{"ids": [1005]}	{"ids": [1005]}	2026-08-07 09:18:38.307274	\N	\N	\N	\N
341	test	component	\N	CREATE_COMPONENT	{"ids": [1006]}	{"ids": [1006]}	2026-08-07 09:18:38.33382	\N	\N	\N	\N
342	test	component	\N	CREATE_COMPONENT	{"ids": [1007]}	{"ids": [1007]}	2026-08-07 09:18:38.352821	\N	\N	\N	\N
343	test	component	\N	DELETE_COMPONENT	{"ids": [997]}	{"ids": [997]}	2026-08-07 09:18:38.376818	\N	\N	\N	\N
344	test	component	\N	DELETE_COMPONENT	{"ids": [998]}	{"ids": [998]}	2026-08-07 09:18:38.395824	\N	\N	\N	\N
345	test	component	\N	DELETE_COMPONENT	{"ids": [999]}	{"ids": [999]}	2026-08-07 09:18:38.409818	\N	\N	\N	\N
346	test	component	\N	DELETE_COMPONENT	{"ids": [1000]}	{"ids": [1000]}	2026-08-07 09:18:38.423823	\N	\N	\N	\N
347	test	component	\N	DELETE_COMPONENT	{"ids": [1001]}	{"ids": [1001]}	2026-08-07 09:18:38.437818	\N	\N	\N	\N
348	test	component	\N	DELETE_COMPONENT	{"ids": [1002]}	{"ids": [1002]}	2026-08-07 09:18:38.453452	\N	\N	\N	\N
349	test	component	\N	DELETE_COMPONENT	{"ids": [1003]}	{"ids": [1003]}	2026-08-07 09:18:38.466448	\N	\N	\N	\N
350	test	component	\N	DELETE_COMPONENT	{"ids": [1004]}	{"ids": [1004]}	2026-08-07 09:18:38.486448	\N	\N	\N	\N
351	test	component	\N	DELETE_COMPONENT	{"ids": [1005]}	{"ids": [1005]}	2026-08-07 09:18:38.504452	\N	\N	\N	\N
352	test	component	\N	DELETE_COMPONENT	{"ids": [1006]}	{"ids": [1006]}	2026-08-07 09:18:38.517446	\N	\N	\N	\N
353	test	component	\N	DELETE_COMPONENT	{"ids": [1007]}	{"ids": [1007]}	2026-08-07 09:18:38.534447	\N	\N	\N	\N
354	verify	component	1008	CREATE_PROJECT	{"id": 1008}	{"id": 1008}	2026-08-07 09:20:14.676163	\N	\N	\N	\N
355	verify	component	1009	CREATE_SCENE	{"id": 1009}	{"id": 1009}	2026-08-07 09:20:14.698162	\N	\N	\N	\N
356	verify	component	\N	CREATE_COMPONENT	{"ids": [1010, 1011]}	{"ids": [1010, 1011]}	2026-08-07 09:20:14.723162	\N	\N	\N	\N
357	verify	component	\N	UPDATE_COMPONENT	{"ids": [1010]}	{"ids": [1010]}	2026-08-07 09:20:14.794102	\N	\N	\N	\N
358	verify	component	\N	DELETE_COMPONENT	{"ids": [1008]}	{"ids": [1008]}	2026-08-07 09:20:14.931642	\N	\N	\N	\N
359	cleanup	component	\N	DELETE_COMPONENT	{"ids": [996]}	{"ids": [996]}	2026-08-07 09:25:14.221969	\N	\N	\N	\N
360	probe	component	\N	CREATE_COMPONENT	{"ids": [1012]}	{"ids": [1012]}	2026-08-07 09:37:46.474876	\N	\N	\N	\N
361	probe	component	\N	DELETE_COMPONENT	{"ids": [1012]}	{"ids": [1012]}	2026-08-07 09:37:46.533414	\N	\N	\N	\N
362	test	component	\N	CREATE_COMPONENT	{"ids": [1013]}	{"ids": [1013]}	2026-08-07 09:42:07.948428	\N	\N	\N	\N
363	test	component	\N	UPDATE_COMPONENT	{"ids": [1013]}	{"ids": [1013]}	2026-08-07 09:42:08.06796	\N	\N	\N	\N
364	test	component	\N	CREATE_COMPONENT	{"ids": [1014]}	{"ids": [1014]}	2026-08-07 09:42:08.118417	\N	\N	\N	\N
365	test	component	\N	UPDATE_COMPONENT	{"ids": [1014]}	{"ids": [1014]}	2026-08-07 09:42:08.157415	\N	\N	\N	\N
366	test	component	\N	UPDATE_COMPONENT	{"ids": [1014]}	{"ids": [1014]}	2026-08-07 09:42:08.201278	\N	\N	\N	\N
367	test	component	\N	UPDATE_COMPONENT	{"ids": [1014]}	{"ids": [1014]}	2026-08-07 09:42:08.255398	\N	\N	\N	\N
368	test	component	\N	CREATE_COMPONENT	{"ids": [1015]}	{"ids": [1015]}	2026-08-07 09:42:08.293948	\N	\N	\N	\N
369	test	component	\N	UPDATE_COMPONENT	{"ids": [1015]}	{"ids": [1015]}	2026-08-07 09:42:08.319948	\N	\N	\N	\N
370	test	component	\N	CREATE_COMPONENT	{"ids": [1016]}	{"ids": [1016]}	2026-08-07 09:42:08.352949	\N	\N	\N	\N
371	test	component	\N	CREATE_COMPONENT	{"ids": [1017]}	{"ids": [1017]}	2026-08-07 09:42:08.385519	\N	\N	\N	\N
372	test	component	\N	CREATE_COMPONENT	{"ids": [1018]}	{"ids": [1018]}	2026-08-07 09:42:08.442514	\N	\N	\N	\N
373	test	component	\N	CREATE_COMPONENT	{"ids": [1019]}	{"ids": [1019]}	2026-08-07 09:42:08.456518	\N	\N	\N	\N
374	test	component	\N	CREATE_COMPONENT	{"ids": [1020]}	{"ids": [1020]}	2026-08-07 09:42:08.483516	\N	\N	\N	\N
375	test	component	\N	UPDATE_COMPONENT	{"ids": [1020]}	{"ids": [1020]}	2026-08-07 09:42:08.503513	\N	\N	\N	\N
376	test	component	\N	CREATE_COMPONENT	{"ids": [1021]}	{"ids": [1021]}	2026-08-07 09:42:08.534516	\N	\N	\N	\N
377	test	component	\N	UPDATE_COMPONENT	{"ids": [1021]}	{"ids": [1021]}	2026-08-07 09:42:08.552512	\N	\N	\N	\N
378	test	component	\N	CREATE_COMPONENT	{"ids": [1022]}	{"ids": [1022]}	2026-08-07 09:42:08.592625	\N	\N	\N	\N
379	test	component	\N	CREATE_COMPONENT	{"ids": [1023]}	{"ids": [1023]}	2026-08-07 09:42:08.617182	\N	\N	\N	\N
380	test	component	\N	CREATE_COMPONENT	{"ids": [1024]}	{"ids": [1024]}	2026-08-07 09:42:08.657676	\N	\N	\N	\N
381	test	component	\N	UPDATE_COMPONENT	{"ids": [1024]}	{"ids": [1024]}	2026-08-07 09:42:08.695675	\N	\N	\N	\N
382	test	component	\N	UPDATE_COMPONENT	{"ids": [1024]}	{"ids": [1024]}	2026-08-07 09:42:08.727211	\N	\N	\N	\N
383	test	component	\N	UPDATE_COMPONENT	{"ids": [1024]}	{"ids": [1024]}	2026-08-07 09:42:08.761211	\N	\N	\N	\N
384	test	component	\N	CREATE_COMPONENT	{"ids": [1025]}	{"ids": [1025]}	2026-08-07 09:42:08.787209	\N	\N	\N	\N
385	test	component	\N	UPDATE_COMPONENT	{"ids": [1025]}	{"ids": [1025]}	2026-08-07 09:42:08.811208	\N	\N	\N	\N
386	test	component	\N	UPDATE_COMPONENT	{"ids": [1025]}	{"ids": [1025]}	2026-08-07 09:42:08.834522	\N	\N	\N	\N
387	test	component	\N	UPDATE_COMPONENT	{"ids": [1025]}	{"ids": [1025]}	2026-08-07 09:42:08.859312	\N	\N	\N	\N
388	test	component	\N	DELETE_COMPONENT	{"ids": [1013]}	{"ids": [1013]}	2026-08-07 09:42:08.87933	\N	\N	\N	\N
389	test	component	\N	DELETE_COMPONENT	{"ids": [1014]}	{"ids": [1014]}	2026-08-07 09:42:08.894327	\N	\N	\N	\N
390	test	component	\N	DELETE_COMPONENT	{"ids": [1015]}	{"ids": [1015]}	2026-08-07 09:42:08.908328	\N	\N	\N	\N
391	test	component	\N	DELETE_COMPONENT	{"ids": [1016]}	{"ids": [1016]}	2026-08-07 09:42:08.923329	\N	\N	\N	\N
392	test	component	\N	DELETE_COMPONENT	{"ids": [1017]}	{"ids": [1017]}	2026-08-07 09:42:08.936323	\N	\N	\N	\N
393	test	component	\N	DELETE_COMPONENT	{"ids": [1018]}	{"ids": [1018]}	2026-08-07 09:42:08.949326	\N	\N	\N	\N
394	test	component	\N	DELETE_COMPONENT	{"ids": [1019]}	{"ids": [1019]}	2026-08-07 09:42:08.962327	\N	\N	\N	\N
395	test	component	\N	DELETE_COMPONENT	{"ids": [1020]}	{"ids": [1020]}	2026-08-07 09:42:08.973324	\N	\N	\N	\N
396	test	component	\N	DELETE_COMPONENT	{"ids": [1021]}	{"ids": [1021]}	2026-08-07 09:42:08.986322	\N	\N	\N	\N
397	test	component	\N	DELETE_COMPONENT	{"ids": [1022]}	{"ids": [1022]}	2026-08-07 09:42:08.998326	\N	\N	\N	\N
398	test	component	\N	DELETE_COMPONENT	{"ids": [1023]}	{"ids": [1023]}	2026-08-07 09:42:09.008325	\N	\N	\N	\N
399	test	component	\N	DELETE_COMPONENT	{"ids": [1024]}	{"ids": [1024]}	2026-08-07 09:42:09.023461	\N	\N	\N	\N
400	test	component	\N	DELETE_COMPONENT	{"ids": [1025]}	{"ids": [1025]}	2026-08-07 09:42:09.040651	\N	\N	\N	\N
401	probe	component	\N	UPDATE_COMPONENT	{"ids": [992]}	{"ids": [992]}	2026-08-07 09:42:27.915646	\N	\N	\N	\N
402	probe	component	\N	UPDATE_COMPONENT	{"ids": [992]}	{"ids": [992]}	2026-08-07 09:42:27.94937	\N	\N	\N	\N
403	probe	component	\N	UPDATE_COMPONENT	{"ids": [992]}	{"ids": [992]}	2026-08-07 09:42:27.986157	\N	\N	\N	\N
404	test	component	\N	CREATE_COMPONENT	{"ids": [1026]}	{"ids": [1026]}	2026-08-07 09:52:57.354633	\N	\N	\N	\N
405	test	component	\N	UPDATE_COMPONENT	{"ids": [1026]}	{"ids": [1026]}	2026-08-07 09:52:57.427202	\N	\N	\N	\N
406	test	component	\N	CREATE_COMPONENT	{"ids": [1027]}	{"ids": [1027]}	2026-08-07 09:52:57.464201	\N	\N	\N	\N
407	test	component	\N	UPDATE_COMPONENT	{"ids": [1027]}	{"ids": [1027]}	2026-08-07 09:52:57.488201	\N	\N	\N	\N
408	test	component	\N	UPDATE_COMPONENT	{"ids": [1027]}	{"ids": [1027]}	2026-08-07 09:52:57.514146	\N	\N	\N	\N
409	test	component	\N	UPDATE_COMPONENT	{"ids": [1027]}	{"ids": [1027]}	2026-08-07 09:52:57.548014	\N	\N	\N	\N
410	test	component	\N	CREATE_COMPONENT	{"ids": [1028]}	{"ids": [1028]}	2026-08-07 09:52:57.577284	\N	\N	\N	\N
411	test	component	\N	UPDATE_COMPONENT	{"ids": [1028]}	{"ids": [1028]}	2026-08-07 09:52:57.596286	\N	\N	\N	\N
412	test	component	\N	CREATE_COMPONENT	{"ids": [1029]}	{"ids": [1029]}	2026-08-07 09:52:57.620284	\N	\N	\N	\N
413	test	component	\N	CREATE_COMPONENT	{"ids": [1030]}	{"ids": [1030]}	2026-08-07 09:52:57.646287	\N	\N	\N	\N
414	test	component	\N	CREATE_COMPONENT	{"ids": [1031]}	{"ids": [1031]}	2026-08-07 09:52:57.700147	\N	\N	\N	\N
415	test	component	\N	CREATE_COMPONENT	{"ids": [1032]}	{"ids": [1032]}	2026-08-07 09:52:57.713147	\N	\N	\N	\N
416	test	component	\N	CREATE_COMPONENT	{"ids": [1033]}	{"ids": [1033]}	2026-08-07 09:52:57.742236	\N	\N	\N	\N
417	test	component	\N	UPDATE_COMPONENT	{"ids": [1033]}	{"ids": [1033]}	2026-08-07 09:52:57.765005	\N	\N	\N	\N
418	test	component	\N	CREATE_COMPONENT	{"ids": [1034]}	{"ids": [1034]}	2026-08-07 09:52:57.793459	\N	\N	\N	\N
419	test	component	\N	UPDATE_COMPONENT	{"ids": [1034]}	{"ids": [1034]}	2026-08-07 09:52:57.810851	\N	\N	\N	\N
420	test	component	\N	CREATE_COMPONENT	{"ids": [1035]}	{"ids": [1035]}	2026-08-07 09:52:57.849528	\N	\N	\N	\N
421	test	component	\N	CREATE_COMPONENT	{"ids": [1036]}	{"ids": [1036]}	2026-08-07 09:52:57.876705	\N	\N	\N	\N
422	test	component	\N	CREATE_COMPONENT	{"ids": [1037]}	{"ids": [1037]}	2026-08-07 09:52:57.915533	\N	\N	\N	\N
423	test	component	\N	UPDATE_COMPONENT	{"ids": [1037]}	{"ids": [1037]}	2026-08-07 09:52:57.947492	\N	\N	\N	\N
424	test	component	\N	UPDATE_COMPONENT	{"ids": [1037]}	{"ids": [1037]}	2026-08-07 09:52:57.970488	\N	\N	\N	\N
425	test	component	\N	UPDATE_COMPONENT	{"ids": [1037]}	{"ids": [1037]}	2026-08-07 09:52:57.993581	\N	\N	\N	\N
426	test	component	\N	CREATE_COMPONENT	{"ids": [1038]}	{"ids": [1038]}	2026-08-07 09:52:58.014765	\N	\N	\N	\N
427	test	component	\N	UPDATE_COMPONENT	{"ids": [1038]}	{"ids": [1038]}	2026-08-07 09:52:58.034579	\N	\N	\N	\N
428	test	component	\N	UPDATE_COMPONENT	{"ids": [1038]}	{"ids": [1038]}	2026-08-07 09:52:58.057583	\N	\N	\N	\N
429	test	component	\N	UPDATE_COMPONENT	{"ids": [1038]}	{"ids": [1038]}	2026-08-07 09:52:58.085584	\N	\N	\N	\N
430	test	component	\N	CREATE_COMPONENT	{"ids": [1039]}	{"ids": [1039]}	2026-08-07 09:52:58.119579	\N	\N	\N	\N
431	test	component	\N	UPDATE_COMPONENT	{"ids": [1039]}	{"ids": [1039]}	2026-08-07 09:52:58.145108	\N	\N	\N	\N
432	test	component	\N	UPDATE_COMPONENT	{"ids": [1039]}	{"ids": [1039]}	2026-08-07 09:52:58.189479	\N	\N	\N	\N
433	test	component	\N	CREATE_COMPONENT	{"ids": [1040]}	{"ids": [1040]}	2026-08-07 09:52:58.212498	\N	\N	\N	\N
434	test	component	\N	DELETE_COMPONENT	{"ids": [1026]}	{"ids": [1026]}	2026-08-07 09:52:58.262494	\N	\N	\N	\N
435	test	component	\N	DELETE_COMPONENT	{"ids": [1027]}	{"ids": [1027]}	2026-08-07 09:52:58.279493	\N	\N	\N	\N
436	test	component	\N	DELETE_COMPONENT	{"ids": [1028]}	{"ids": [1028]}	2026-08-07 09:52:58.295493	\N	\N	\N	\N
437	test	component	\N	DELETE_COMPONENT	{"ids": [1029]}	{"ids": [1029]}	2026-08-07 09:52:58.312588	\N	\N	\N	\N
438	test	component	\N	DELETE_COMPONENT	{"ids": [1030]}	{"ids": [1030]}	2026-08-07 09:52:58.334587	\N	\N	\N	\N
439	test	component	\N	DELETE_COMPONENT	{"ids": [1031]}	{"ids": [1031]}	2026-08-07 09:52:58.351587	\N	\N	\N	\N
440	test	component	\N	DELETE_COMPONENT	{"ids": [1032]}	{"ids": [1032]}	2026-08-07 09:52:58.366591	\N	\N	\N	\N
441	test	component	\N	DELETE_COMPONENT	{"ids": [1033]}	{"ids": [1033]}	2026-08-07 09:52:58.382584	\N	\N	\N	\N
442	test	component	\N	DELETE_COMPONENT	{"ids": [1034]}	{"ids": [1034]}	2026-08-07 09:52:58.396121	\N	\N	\N	\N
443	test	component	\N	DELETE_COMPONENT	{"ids": [1035]}	{"ids": [1035]}	2026-08-07 09:52:58.409137	\N	\N	\N	\N
444	test	component	\N	DELETE_COMPONENT	{"ids": [1036]}	{"ids": [1036]}	2026-08-07 09:52:58.423134	\N	\N	\N	\N
445	test	component	\N	DELETE_COMPONENT	{"ids": [1037]}	{"ids": [1037]}	2026-08-07 09:52:58.436148	\N	\N	\N	\N
446	test	component	\N	DELETE_COMPONENT	{"ids": [1038]}	{"ids": [1038]}	2026-08-07 09:52:58.45615	\N	\N	\N	\N
447	test	component	\N	DELETE_COMPONENT	{"ids": [1039]}	{"ids": [1039]}	2026-08-07 09:52:58.470152	\N	\N	\N	\N
448	test	component	\N	DELETE_COMPONENT	{"ids": [1040]}	{"ids": [1040]}	2026-08-07 09:52:58.485146	\N	\N	\N	\N
449	tpl-probe	template	35	CREATE_TEMPLATE	\N	\N	2026-08-07 09:54:25.462351	\N	\N	\N	\N
450	tpl-probe	template	35	UPDATE_TEMPLATE	\N	\N	2026-08-07 09:54:25.4879	\N	\N	\N	\N
451	tpl-probe	template	36	CREATE_TEMPLATE	\N	\N	2026-08-07 09:56:03.882896	\N	\N	\N	\N
452	tpl-probe	template	36	UPDATE_TEMPLATE	\N	\N	2026-08-07 09:56:03.995227	\N	\N	\N	\N
453	tpl-probe	template	36	UPDATE_TEMPLATE	\N	\N	2026-08-07 09:56:04.024227	\N	\N	\N	\N
454	cleanup	template	35	DELETE_TEMPLATE	\N	\N	2026-08-07 09:56:43.140021	\N	\N	\N	\N
455	cleanup	template	36	DELETE_TEMPLATE	\N	\N	2026-08-07 09:56:43.153569	\N	\N	\N	\N
456	test	component	\N	CREATE_COMPONENT	{"ids": [1041]}	{"ids": [1041]}	2026-08-07 09:58:46.253921	\N	\N	\N	\N
457	test	component	\N	UPDATE_COMPONENT	{"ids": [1041]}	{"ids": [1041]}	2026-08-07 09:58:46.342919	\N	\N	\N	\N
458	test	component	\N	CREATE_COMPONENT	{"ids": [1042]}	{"ids": [1042]}	2026-08-07 09:58:46.381438	\N	\N	\N	\N
459	test	component	\N	UPDATE_COMPONENT	{"ids": [1042]}	{"ids": [1042]}	2026-08-07 09:58:46.408436	\N	\N	\N	\N
460	test	component	\N	UPDATE_COMPONENT	{"ids": [1042]}	{"ids": [1042]}	2026-08-07 09:58:46.443438	\N	\N	\N	\N
461	test	component	\N	UPDATE_COMPONENT	{"ids": [1042]}	{"ids": [1042]}	2026-08-07 09:58:46.473436	\N	\N	\N	\N
462	test	component	\N	CREATE_COMPONENT	{"ids": [1043]}	{"ids": [1043]}	2026-08-07 09:58:46.500443	\N	\N	\N	\N
463	test	component	\N	UPDATE_COMPONENT	{"ids": [1043]}	{"ids": [1043]}	2026-08-07 09:58:46.524437	\N	\N	\N	\N
464	test	component	\N	CREATE_COMPONENT	{"ids": [1044]}	{"ids": [1044]}	2026-08-07 09:58:46.557435	\N	\N	\N	\N
465	test	component	\N	CREATE_COMPONENT	{"ids": [1045]}	{"ids": [1045]}	2026-08-07 09:58:46.590435	\N	\N	\N	\N
466	test	component	\N	CREATE_COMPONENT	{"ids": [1046]}	{"ids": [1046]}	2026-08-07 09:58:46.634432	\N	\N	\N	\N
467	test	component	\N	CREATE_COMPONENT	{"ids": [1047]}	{"ids": [1047]}	2026-08-07 09:58:46.645432	\N	\N	\N	\N
468	test	component	\N	CREATE_COMPONENT	{"ids": [1048]}	{"ids": [1048]}	2026-08-07 09:58:46.671431	\N	\N	\N	\N
469	test	component	\N	UPDATE_COMPONENT	{"ids": [1048]}	{"ids": [1048]}	2026-08-07 09:58:46.68743	\N	\N	\N	\N
470	test	component	\N	CREATE_COMPONENT	{"ids": [1049]}	{"ids": [1049]}	2026-08-07 09:58:46.708434	\N	\N	\N	\N
471	test	component	\N	UPDATE_COMPONENT	{"ids": [1049]}	{"ids": [1049]}	2026-08-07 09:58:46.721429	\N	\N	\N	\N
472	test	component	\N	CREATE_COMPONENT	{"ids": [1050]}	{"ids": [1050]}	2026-08-07 09:58:46.745413	\N	\N	\N	\N
473	test	component	\N	CREATE_COMPONENT	{"ids": [1051]}	{"ids": [1051]}	2026-08-07 09:58:46.762918	\N	\N	\N	\N
474	test	component	\N	CREATE_COMPONENT	{"ids": [1052]}	{"ids": [1052]}	2026-08-07 09:58:46.791918	\N	\N	\N	\N
475	test	component	\N	UPDATE_COMPONENT	{"ids": [1052]}	{"ids": [1052]}	2026-08-07 09:58:46.819155	\N	\N	\N	\N
476	test	component	\N	UPDATE_COMPONENT	{"ids": [1052]}	{"ids": [1052]}	2026-08-07 09:58:46.837148	\N	\N	\N	\N
477	test	component	\N	UPDATE_COMPONENT	{"ids": [1052]}	{"ids": [1052]}	2026-08-07 09:58:46.85715	\N	\N	\N	\N
478	test	component	\N	CREATE_COMPONENT	{"ids": [1053]}	{"ids": [1053]}	2026-08-07 09:58:46.877149	\N	\N	\N	\N
479	test	component	\N	UPDATE_COMPONENT	{"ids": [1053]}	{"ids": [1053]}	2026-08-07 09:58:46.894153	\N	\N	\N	\N
480	test	component	\N	UPDATE_COMPONENT	{"ids": [1053]}	{"ids": [1053]}	2026-08-07 09:58:46.916148	\N	\N	\N	\N
481	test	component	\N	UPDATE_COMPONENT	{"ids": [1053]}	{"ids": [1053]}	2026-08-07 09:58:46.937149	\N	\N	\N	\N
482	test	component	\N	CREATE_COMPONENT	{"ids": [1054]}	{"ids": [1054]}	2026-08-07 09:58:46.957716	\N	\N	\N	\N
483	test	component	\N	UPDATE_COMPONENT	{"ids": [1054]}	{"ids": [1054]}	2026-08-07 09:58:46.972711	\N	\N	\N	\N
484	test	component	\N	UPDATE_COMPONENT	{"ids": [1054]}	{"ids": [1054]}	2026-08-07 09:58:47.006712	\N	\N	\N	\N
485	test	component	\N	CREATE_COMPONENT	{"ids": [1055]}	{"ids": [1055]}	2026-08-07 09:58:47.024267	\N	\N	\N	\N
486	test	component	\N	CREATE_COMPONENT	{"ids": [1056]}	{"ids": [1056]}	2026-08-07 09:58:47.059267	\N	\N	\N	\N
487	test	component	\N	DELETE_COMPONENT	{"ids": [1041]}	{"ids": [1041]}	2026-08-07 09:58:47.250322	\N	\N	\N	\N
488	test	component	\N	DELETE_COMPONENT	{"ids": [1042]}	{"ids": [1042]}	2026-08-07 09:58:47.262763	\N	\N	\N	\N
489	test	component	\N	DELETE_COMPONENT	{"ids": [1043]}	{"ids": [1043]}	2026-08-07 09:58:47.275288	\N	\N	\N	\N
490	test	component	\N	DELETE_COMPONENT	{"ids": [1044]}	{"ids": [1044]}	2026-08-07 09:58:47.288293	\N	\N	\N	\N
491	test	component	\N	DELETE_COMPONENT	{"ids": [1045]}	{"ids": [1045]}	2026-08-07 09:58:47.301301	\N	\N	\N	\N
492	test	component	\N	DELETE_COMPONENT	{"ids": [1046]}	{"ids": [1046]}	2026-08-07 09:58:47.313302	\N	\N	\N	\N
493	test	component	\N	DELETE_COMPONENT	{"ids": [1047]}	{"ids": [1047]}	2026-08-07 09:58:47.329302	\N	\N	\N	\N
494	test	component	\N	DELETE_COMPONENT	{"ids": [1048]}	{"ids": [1048]}	2026-08-07 09:58:47.343302	\N	\N	\N	\N
495	test	component	\N	DELETE_COMPONENT	{"ids": [1049]}	{"ids": [1049]}	2026-08-07 09:58:47.3553	\N	\N	\N	\N
496	test	component	\N	DELETE_COMPONENT	{"ids": [1050]}	{"ids": [1050]}	2026-08-07 09:58:47.365305	\N	\N	\N	\N
497	test	component	\N	DELETE_COMPONENT	{"ids": [1051]}	{"ids": [1051]}	2026-08-07 09:58:47.376304	\N	\N	\N	\N
498	test	component	\N	DELETE_COMPONENT	{"ids": [1052]}	{"ids": [1052]}	2026-08-07 09:58:47.387302	\N	\N	\N	\N
499	test	component	\N	DELETE_COMPONENT	{"ids": [1053]}	{"ids": [1053]}	2026-08-07 09:58:47.3983	\N	\N	\N	\N
500	test	component	\N	DELETE_COMPONENT	{"ids": [1054]}	{"ids": [1054]}	2026-08-07 09:58:47.408832	\N	\N	\N	\N
501	test	component	\N	DELETE_COMPONENT	{"ids": [1055]}	{"ids": [1055]}	2026-08-07 09:58:47.418846	\N	\N	\N	\N
502	test	component	\N	DELETE_COMPONENT	{"ids": [1056]}	{"ids": [1056]}	2026-08-07 09:58:47.427844	\N	\N	\N	\N
503	david	component	\N	CREATE_COMPONENT	{"ids": [991, 992, 993]}	{"ids": [991, 992, 993]}	2026-08-07 10:05:57.221793	\N	\N	\N	\N
504	david	component	\N	CREATE_COMPONENT	{"ids": [991, 992, 993]}	{"ids": [991, 992, 993]}	2026-08-07 10:06:12.540405	\N	\N	\N	\N
505	david	component	\N	CREATE_COMPONENT	{"ids": [991, 992, 993]}	{"ids": [991, 992, 993]}	2026-08-07 11:04:24.454626	\N	\N	\N	\N
506	david	component	\N	CREATE_COMPONENT	{"ids": [991, 992, 993]}	{"ids": [991, 992, 993]}	2026-08-07 11:09:48.543894	\N	\N	\N	\N
507	fix-colors	component	\N	UPDATE_COMPONENT	{"ids": [992]}	{"ids": [992]}	2026-08-07 11:48:23.474572	\N	\N	\N	\N
508	fix-colors	component	\N	UPDATE_COMPONENT	{"ids": [993]}	{"ids": [993]}	2026-08-07 11:48:23.501572	\N	\N	\N	\N
509	david2	component	\N	CREATE_COMPONENT	{"ids": [991, 992, 993]}	{"ids": [991, 992, 993]}	2026-08-11 13:59:55.395049	\N	\N	\N	\N
510	david2	component	\N	CREATE_COMPONENT	{"ids": [991, 992, 993]}	{"ids": [991, 992, 993]}	2026-08-11 14:08:31.421287	\N	\N	\N	\N
511	david2	component_property	176	CREATE_PROPERTY	{"id": 176}	{"id": 176}	2026-08-11 14:31:03.646816	\N	\N	\N	\N
512	david2	component	\N	CREATE_COMPONENT	{"ids": [991, 992, 993]}	{"ids": [991, 992, 993]}	2026-08-11 14:38:31.440481	\N	\N	\N	\N
513	david	component	1057	CREATE_PROJECT	{"id": 1057}	{"id": 1057}	2026-08-17 14:47:25.166705	\N	\N	\N	\N
514	david	component	1058	CREATE_SCENE	{"id": 1058}	{"id": 1058}	2026-08-17 14:47:44.489388	\N	\N	\N	\N
531	david2	component	\N	UPDATE_COMPONENT	{"ids": [1065, 1076, 1077, 1078]}	{"ids": [1065, 1076, 1077, 1078]}	2026-08-17 15:37:06.125675	\N	\N	\N	\N
515	david2	component	\N	UPDATE_COMPONENT	{"ids": [1059]}	{"ids": [1059]}	2026-08-17 15:25:31.766577	\N	\N	\N	\N
522	david2	component	\N	UPDATE_COMPONENT	{"ids": [1065, 1066]}	{"ids": [1065, 1066]}	2026-08-17 15:34:13.101825	\N	\N	\N	\N
516	david2	component	\N	UPDATE_COMPONENT	{"ids": [1060, 1059, 1061]}	{"ids": [1060, 1059, 1061]}	2026-08-17 15:26:05.457637	\N	\N	\N	\N
517	david2	component	\N	UPDATE_COMPONENT	{"ids": [1060, 1059, 1061, 1062]}	{"ids": [1060, 1059, 1061, 1062]}	2026-08-17 15:29:34.361782	\N	\N	\N	\N
518	david2	component	\N	UPDATE_COMPONENT	{"ids": [1063]}	{"ids": [1063]}	2026-08-17 15:30:39.049468	\N	\N	\N	\N
519	david2	component	\N	UPDATE_COMPONENT	{"ids": [1064]}	{"ids": [1064]}	2026-08-17 15:32:29.326374	\N	\N	\N	\N
520	david2	component	\N	UPDATE_COMPONENT	{"ids": [1065]}	{"ids": [1065]}	2026-08-17 15:33:19.838727	\N	\N	\N	\N
523	david2	component	\N	UPDATE_COMPONENT	{"ids": [1065]}	{"ids": [1065]}	2026-08-17 15:34:17.600463	\N	\N	\N	\N
521	david2	component	\N	UPDATE_COMPONENT	{"ids": [1065, 1066]}	{"ids": [1065, 1066]}	2026-08-17 15:33:36.724264	\N	\N	\N	\N
524	david2	component	\N	UPDATE_COMPONENT	{"ids": [1065, 1067, 1068, 1069]}	{"ids": [1065, 1067, 1068, 1069]}	2026-08-17 15:34:29.426668	\N	\N	\N	\N
532	david2	component	\N	UPDATE_COMPONENT	{"ids": [1065]}	{"ids": [1065]}	2026-08-17 15:37:07.297816	\N	\N	\N	\N
525	david2	component	\N	UPDATE_COMPONENT	{"ids": [1065, 1067, 1068, 1069]}	{"ids": [1065, 1067, 1068, 1069]}	2026-08-17 15:34:39.559445	\N	\N	\N	\N
526	david2	component	\N	UPDATE_COMPONENT	{"ids": [1065]}	{"ids": [1065]}	2026-08-17 15:36:01.403929	\N	\N	\N	\N
527	david2	component	\N	UPDATE_COMPONENT	{"ids": [1065, 1070, 1071, 1072]}	{"ids": [1065, 1070, 1071, 1072]}	2026-08-17 15:36:03.991435	\N	\N	\N	\N
528	david2	component	\N	UPDATE_COMPONENT	{"ids": [1065]}	{"ids": [1065]}	2026-08-17 15:36:54.80356	\N	\N	\N	\N
529	david2	component	\N	UPDATE_COMPONENT	{"ids": [1065]}	{"ids": [1065]}	2026-08-17 15:36:56.436069	\N	\N	\N	\N
530	david2	component	\N	UPDATE_COMPONENT	{"ids": [1065, 1073, 1074, 1075]}	{"ids": [1065, 1073, 1074, 1075]}	2026-08-17 15:37:01.034932	\N	\N	\N	\N
533	david2	component	\N	UPDATE_COMPONENT	{"ids": [1065, 1079, 1080, 1081]}	{"ids": [1065, 1079, 1080, 1081]}	2026-08-17 15:37:09.846703	\N	\N	\N	\N
534	david2	component	\N	UPDATE_COMPONENT	{"ids": [1065, 1082]}	{"ids": [1065, 1082]}	2026-08-17 15:37:22.197363	\N	\N	\N	\N
535	david2	component	\N	UPDATE_COMPONENT	{"ids": [1065, 1082]}	{"ids": [1065, 1082]}	2026-08-17 15:37:25.102474	\N	\N	\N	\N
536	david2	component	\N	UPDATE_COMPONENT	{"ids": [1065, 1083, 1084, 1085]}	{"ids": [1065, 1083, 1084, 1085]}	2026-08-17 15:37:28.13817	\N	\N	\N	\N
\.


--
-- Name: command_log_id_seq; Type: SEQUENCE SET; Schema: editor; Owner: postgres
--

SELECT pg_catalog.setval('editor.command_log_id_seq', 536, true);


--
-- Name: command_log command_log_pkey; Type: CONSTRAINT; Schema: editor; Owner: postgres
--

ALTER TABLE ONLY editor.command_log
    ADD CONSTRAINT command_log_pkey PRIMARY KEY (id);


--
-- Name: idx_editor_command_log_created_at; Type: INDEX; Schema: editor; Owner: postgres
--

CREATE INDEX idx_editor_command_log_created_at ON editor.command_log USING btree (created_at);


--
-- Name: idx_editor_command_log_entity_type_id; Type: INDEX; Schema: editor; Owner: postgres
--

CREATE INDEX idx_editor_command_log_entity_type_id ON editor.command_log USING btree (entity_type, entity_id);


--
-- Name: idx_editor_command_log_user_name; Type: INDEX; Schema: editor; Owner: postgres
--

CREATE INDEX idx_editor_command_log_user_name ON editor.command_log USING btree (user_name);


--
-- PostgreSQL database dump complete
--

