-- Выполняется runtime при каждом старте (spring.sql.init). Идемпотентен.
-- Схема runtime: таблицы в ней создаёт Hibernate (ddl-auto: update), но не саму схему.
CREATE SCHEMA IF NOT EXISTS runtime;

-- Схема automation: рабочее состояние фоновых задач. Раньше ей владел сервис automation.
CREATE SCHEMA IF NOT EXISTS automation;
-- Значения свойств проекта, которые пишут скрипты (on_change, кнопки). В памяти runtime они
-- живут в ProjectRuntime.propertyValues; без этой таблицы перезапуск возвращал режимы и флаги
-- скриптов к default_value (scada-vrkf). Значение telemetry-тегов сюда не пишется.
CREATE TABLE IF NOT EXISTS runtime.property_value (
    project_id  bigint      NOT NULL,
    property_id bigint      NOT NULL,
    value       jsonb       NOT NULL,
    updated_at  timestamptz NOT NULL,
    PRIMARY KEY (project_id, property_id)
);

CREATE TABLE IF NOT EXISTS automation.task_checkpoint (
    project_id      bigint      NOT NULL,
    task_id         bigint      NOT NULL,
    definition_hash text        NOT NULL,
    state           jsonb       NOT NULL,
    updated_at      timestamptz NOT NULL,
    PRIMARY KEY (project_id, task_id)
);

CREATE TABLE IF NOT EXISTS automation.variable_value (
    project_id bigint      NOT NULL,
    name       text        NOT NULL,
    value      jsonb,
    quality    text        NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (project_id, name)
);

CREATE TABLE IF NOT EXISTS automation.task_status (
    project_id       bigint      NOT NULL,
    task_id          bigint      NOT NULL,
    name             text        NOT NULL,
    state            text        NOT NULL,
    last_run_at      timestamptz,
    last_duration_ms bigint,
    last_error       text,
    error_count      bigint      NOT NULL,
    owner_instance   text,
    updated_at       timestamptz NOT NULL,
    PRIMARY KEY (project_id, task_id)
);

-- Доработка базы, оставшейся от сервиса automation (этап 2А, 17.09.2026).
ALTER TABLE automation.task_status ADD COLUMN IF NOT EXISTS last_lag_ms bigint;
ALTER TABLE automation.task_checkpoint DROP COLUMN IF EXISTS epoch;
ALTER TABLE automation.variable_value DROP COLUMN IF EXISTS epoch;
DROP TABLE IF EXISTS automation.partition_epoch;

-- Аренда драйверов этапа 1 заменена назначениями (этап 2Б).
DROP TABLE IF EXISTS runtime.driver_lease;

-- Архив тегов (дизайн 2026-09-28-tag-archive). Пишет ArchiveWriter, только изменения.
-- Секции по суткам создаёт и удаляет ArchivePartitionManager; DEFAULT ловит строку, если
-- секция не успела появиться (сбой задачи, перевод часов). Hibernate секционированные
-- таблицы не создаёт — поэтому здесь.
CREATE TABLE IF NOT EXISTS runtime.archive_tag (
    id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    path text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS runtime.tag_archive (
    tag        integer          NOT NULL,
    ts         timestamptz      NOT NULL,
    value_num  double precision,
    value_text text,
    good       boolean          NOT NULL
) PARTITION BY RANGE (ts);

CREATE INDEX IF NOT EXISTS tag_archive_tag_ts_idx ON runtime.tag_archive (tag, ts);

CREATE TABLE IF NOT EXISTS runtime.tag_archive_default PARTITION OF runtime.tag_archive DEFAULT;

-- Журнал действий оператора: кто, когда, что нажал. Секции — как у архива.
CREATE TABLE IF NOT EXISTS runtime.action_log (
    id           bigint GENERATED BY DEFAULT AS IDENTITY,
    ts           timestamptz NOT NULL,
    username     text,
    project_id   bigint,
    kind         text        NOT NULL,
    component_id bigint,
    component    text,
    target       text,
    tags         jsonb,
    outcome      text        NOT NULL,
    error        text,
    PRIMARY KEY (id, ts)
) PARTITION BY RANGE (ts);

CREATE INDEX IF NOT EXISTS action_log_project_ts_idx ON runtime.action_log (project_id, ts);

CREATE TABLE IF NOT EXISTS runtime.action_log_default PARTITION OF runtime.action_log DEFAULT;
